# Generated by Django 4.2.6 on 2023-11-01 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("content", models.TextField()),
                ("video_url", models.URLField(null=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
